name: E2E Cookiecutters

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths: ["cookiecutter/**", "e2e-tests/cookiecutters/**"]
  push:
    branches: [main]
    paths: ["cookiecutter/**", "e2e-tests/cookiecutters/**"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  FORCE_COLOR: "1"

jobs:
  lint:
    name: Lint ${{ matrix.cookiecutter }}, Replay ${{ matrix.replay }} on ${{ matrix.python-version }} ${{ matrix.python-version }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      NOXSESSION: ${{ matrix.session }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - {session: "test_cookiecutter(replay_file_path='./e2e-tests/cookiecutters/tap-graphql-jwt.json')", python-version: "3.10",  os: "ubuntu-latest" }
          - {session: "test_cookiecutter(replay_file_path='./e2e-tests/cookiecutters/tap-rest-api_key-github.json')", python-version: "3.10",  os: "ubuntu-latest" }
          - {session: "test_cookiecutter(replay_file_path='./e2e-tests/cookiecutters/tap-rest-basic_auth.json')", python-version: "3.10",  os: "ubuntu-latest" }
          - {session: "test_cookiecutter(replay_file_path='./e2e-tests/cookiecutters/tap-rest-bearer_token.json')", python-version: "3.10",  os: "ubuntu-latest" }
          - {session: "test_cookiecutter(replay_file_path='./e2e-tests/cookiecutters/tap-rest-custom.json')", python-version: "3.10",  os: "ubuntu-latest" }
          - {session: "test_cookiecutter(replay_file_path='./e2e-tests/cookiecutters/tap-rest-jwt.json')", python-version: "3.10",  os: "ubuntu-latest" }
          - {session: "test_cookiecutter(replay_file_path='./e2e-tests/cookiecutters/tap-rest-oauth2.json')", python-version: "3.10",  os: "ubuntu-latest" }
          - {session: "test_cookiecutter(replay_file_path='./e2e-tests/cookiecutters/tap-other-custom.json')", python-version: "3.10",  os: "ubuntu-latest" }
          - {session: "test_cookiecutter(replay_file_path='./e2e-tests/cookiecutters/tap-sql-custom.json')", python-version: "3.10",  os: "ubuntu-latest" }
          - {session: "test_cookiecutter(replay_file_path='./e2e-tests/cookiecutters/target-per_record.json')", python-version: "3.10",  os: "ubuntu-latest" }


    steps:
    - name: Check out the repository
      uses: actions/checkout@v3.3.0

    - name: Install Poetry & Tox
      env:
        PIP_CONSTRAINT: .github/workflows/constraints.txt
      run: |
        pipx install poetry
        poetry --version
        pipx install tox
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4.5.0
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
        cache: 'pip'
        cache-dependency-path: 'poetry.lock'

    - name: Upgrade pip
      env:
        PIP_CONSTRAINT: .github/workflows/constraints.txt
      run: |
        pip install pip
        pip --version
    - name: Install Nox
      env:
        PIP_CONSTRAINT: .github/workflows/constraints.txt
      run: |
        pipx install --pip-args=--constraint=.github/workflows/constraints.txt nox
        pipx inject --pip-args=--constraint=.github/workflows/constraints.txt nox nox-poetry
        nox --version
      
    - name: Run Nox
      run: |
        nox --python=${{ matrix.python-version }}